config/routes.rb
Rails.application.routes.draw do
  
  resources :trainer_cards
  devise_for :trainers

  authenticated :trainer do
    root 'pokemons#index', as: :authenticated_root
  end

  unauthenticated :trainer do
    root "splash#index", as: :unauthenticated_root
  end
  

  resources :pokemons do
    collection do
      get 'collect'
      post 'update_create_pokemon'
    end
  end

  get 'trainer_card/for_trainer/:id' => 'trainer_cards#for_trainer', as: :trainers_card
end

app/models/trainer_card.rb
class TrainerCard < ApplicationRecord
    validate :has_at_least_one_pokemon

    def has_at_least_one_pokemon
        values = [self.pokemon_one, self.pokemon_two, self.pokemon_three, self.pokemon_four, self.pokemon_five, self.pokemon_six]

        if !values.any?
            errors.add(:model_years, "Prof. Oak - You cant use this here. At least one pokemon is required.")
        end
    end
end

app/controllers/trainer_cards_controller.rb
class TrainerCardsController < ApplicationController
  before_action :authenticate_trainer!
  before_action :set_trainer_card, only: [:show, :edit, :update, :destroy]
  before_action :set_trainer_and_pokemon

  # GET /trainer_cards
  # GET /trainer_cards.json
  def index
    @trainer_cards = TrainerCard.all
  end

  # GET /trainer_cards/1
  # GET /trainer_cards/1.json
  def show
  end

  # GET /trainer_cards/new
  def new
    @trainer_card = TrainerCard.new
  end

  # GET /trainer_cards/1/edit
  def edit
    @pokemon = Pokemon.all
  end

  # POST /trainer_cards
  # POST /trainer_cards.json
  def create
    @trainer_card = TrainerCard.new(trainer_card_params)

    respond_to do |format|
      if @trainer_card.save
        format.html { redirect_to @trainer_card, notice: 'Trainer card was successfully created.' }
        format.json { render :show, status: :created, location: @trainer_card }
      else
        format.html { render :new }
        format.json { render json: @trainer_card.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /trainer_cards/1
  # PATCH/PUT /trainer_cards/1.json
  def update
    respond_to do |format|
      if @trainer_card.update(trainer_card_params)
        format.html { redirect_to @trainer_card, notice: 'Trainer card was successfully updated.' }
        format.json { render :show, status: :ok, location: @trainer_card }
      else
        format.html { render :edit }
        format.json { render json: @trainer_card.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trainer_cards/1
  # DELETE /trainer_cards/1.json
  def destroy
    @trainer_card.destroy
    respond_to do |format|
      format.html { redirect_to trainer_cards_url, notice: 'Trainer card was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def for_trainer 
    @trainer_card = TrainerCard.find_by_trainer_id(params[:id])
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_trainer_card
      @trainer_card = TrainerCard.find(params[:id])
    end

    def set_trainer_and_pokemon
      @pokemons = Pokemon.all
      @current_trainer = current_trainer
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def trainer_card_params
      params.require(:trainer_card).permit(:trainer_id, :pokemon_one, :pokemon_two, :pokemon_three, :pokemon_four, :pokemon_five, :pokemon_six)
    end
end

app/helpers/trainer_cards_helper.rb
module TrainerCardsHelper
end

app/views/trainer_cards/_card.html.haml
.container-fluid
  .row.justify-content-md-center
    .trainer-card.col-sm-10
      - if trainer
        .col-sm-4
          .trainerid
            = "Trainer ID: #{current_trainer.id}"
          .trainerpic
            = image_tag("#{current_trainer.gender.downcase}.png", :alt => current_trainer.gender)
          .trainername
            = current_trainer.name


      .trainer-card-left.col-sm-8
        .trainer-pokemon
          - link = trainer ? true : false

          - ['one', 'two', 'three', 'four', 'five', 'six'].each do |num|
            .slot.col-sm-3{class: "slot#{num}", data: {slot: num}}
              - if card && card["pokemon_#{num}"]
                = render partial: "layouts/display_pokemon", locals: {pokemon: Pokemon.find_by_pid(card["pokemon_#{num}"]), link: true}
      
        .trainer-pokemon-info
          - if edit
            = "First select a slot above. Then click on a Pokemon to assign it to that slot."
      
      - if edit
        .trainer-card-right.col-sm-4
          .search-title
            = "Search for you Pokemon"
          .pokemon-search
            = render partial: "layouts/pokemon_entry", locals: {pokemons: pokemons}
          .info
            = "Scroll"

app/views/trainer_cards/_form.html.haml
= form_for @trainer_card do |f|
  - if @trainer_card.errors.any?
    #error_explanation
      %h2= "#{pluralize(@trainer_card.errors.count, "error")} prohibited this trainer_card from being saved:"
      %ul
        - @trainer_card.errors.full_messages.each do |msg|
          %li= msg
          
  .field
    = f.hidden_field :trainer_id, value: @current_trainer.id

    = f.hidden_field :pokemon_one

    = f.hidden_field :pokemon_two

    = f.hidden_field :pokemon_three

    = f.hidden_field :pokemon_four

    = f.hidden_field :pokemon_five

    = f.hidden_field :pokemon_six

  .container-fluid
    .row.justify-content-md-center
      .trainer-card.col-sm-10
        .trainer-card-left.col-sm-8
          .trainer-pokemon
            .slot.slotone.col-sm-3.active{data: {slot: "one"}}
            .slot.slottwo.col-sm-3{data: {slot: "two"}}
            .slot.slotthree.col-sm-3{data: {slot: "three"}}

            .slot.slotfour.col-sm-3{data: {slot: "four"}}
            .slot.slotfive.col-sm-3{data: {slot: "five"}}
            .slot.slotsix.col-sm-3{data: {slot: "six"}}
          
          .trainer-pokemon-info
            = "First select a slot above. Then click on a Pokemon to assign it to that slot."

        .trainer-card-right.col-sm-4
          .search-title
            = "Search for you Pokemon"
          .pokemon-search
            = render partial: "layouts/pokemon_entry", locals: {pokemons: @pokemons, link: false}
          .info
            = "Scroll"


  
  .actions
    = f.submit 'Save', class: "submit-card"

app/views/trainer_cards/_show_card.html.haml
= render partial: "card", locals: {pokemons: @pokemons, edit: false, 
                                  trainer: true, current_trainer: @current_trainer, card: @trainer_card}

.controls

  - if @trainer_card
    = link_to 'Edit', edit_trainer_card_path(@trainer_card)
    \|
  = link_to 'Back', pokemons_path()

app/views/trainer_cards/edit.html.haml
%h1 Editing trainer_card

= render 'form'

= link_to 'Show', @trainer_card
\|
= link_to 'Back', pokemons_path()

app/views/trainer_cards/for_trainer.html.haml
= render partial: "show_card"

app/views/trainer_cards/index.html.haml
%h1 Listing trainer_cards

%table
  %thead
    %tr
      %th Trainer
      %th Pokemon one
      %th Pokemon two
      %th Pokemon three
      %th Pokemon four
      %th Pokemon five
      %th Pokemon six
      %th
      %th
      %th

  %tbody
    - @trainer_cards.each do |trainer_card|
      %tr
        %td= trainer_card.trainer_id
        %td= trainer_card.pokemon_one
        %td= trainer_card.pokemon_two
        %td= trainer_card.pokemon_three
        %td= trainer_card.pokemon_four
        %td= trainer_card.pokemon_five
        %td= trainer_card.pokemon_six
        %td= link_to 'Show', trainer_card
        %td= link_to 'Edit', edit_trainer_card_path(trainer_card)
        %td= link_to 'Destroy', trainer_card, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Trainer card', new_trainer_card_path

app/views/trainer_cards/new.html.haml
.container.splash-header
    %h1.pokemon Register your Pokemon

= render 'form'

= link_to 'Back', pokemons_path()

app/views/trainer_cards/show.html.haml
= render partial: "show_card"