config/routes.rb
Rails.application.routes.draw do
  
  resources :trainer_cards
  devise_for :trainers

  authenticated :trainer do
    root 'pokemons#index', as: :authenticated_root
  end

  unauthenticated :trainer do
    root "splash#index", as: :unauthenticated_root
  end
  

  resources :pokemons do
    collection do
      get 'collect'
      post 'update_create_pokemon'
    end
  end

  get 'trainer_card/for_trainer/:id' => 'trainer_cards#for_trainer', as: :trainers_card
end

app/models/pokemon.rb
class Pokemon < ApplicationRecord
end

app/controllers/pokemons_controller.rb
class PokemonsController < ApplicationController
  before_action :authenticate_trainer!
  before_action :set_pokemon, only: [:show, :edit, :update, :destroy]

  # GET /pokemons
  # GET /pokemons.json
  def index
    if current_trainer.email == "profoak@gmail.com"
      redirect_to collect_pokemons_path()
    elsif current_trainer.trainer_card == nil
      redirect_to new_trainer_card_path() 
    else
      @pokemons = Pokemon.all
    end
  end

  # GET /pokemons/1
  # GET /pokemons/1.json
  def show
  end

  # GET /pokemons/new
  def new
    @pokemon = Pokemon.new
  end

  def collect
  end

  # GET /pokemons/1/edit
  def edit
  end

  # POST /pokemons
  # POST /pokemons.json
  def create
    @pokemon = Pokemon.new(pokemon_params)

    respond_to do |format|
      if @pokemon.save
        format.html { redirect_to @pokemon, notice: 'Pokemon was successfully created.' }
        format.json { render :show, status: :created, location: @pokemon }
      else
        format.html { render :new }
        format.json { render json: @pokemon.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pokemons/1
  # PATCH/PUT /pokemons/1.json
  def update
    respond_to do |format|
      if @pokemon.update(pokemon_params)
        format.html { redirect_to @pokemon, notice: 'Pokemon was successfully updated.' }
        format.json { render :show, status: :ok, location: @pokemon }
      else
        format.html { render :edit }
        format.json { render json: @pokemon.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pokemons/1
  # DELETE /pokemons/1.json
  def destroy
    @pokemon.destroy
    respond_to do |format|
      format.html { redirect_to pokemons_url, notice: 'Pokemon was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  def update_create_pokemon 
    pokemon = format_pokemon_ids params[:pokemon][:collection]

    # Also get move types
    get_move_types

    pokemon.each do |idenifier|
      monster = Poke::Dex.get_pokemon(idenifier)
      mon = Pokemon.where(pid: monster[:pid])

      if mon.empty?
        Pokemon.create(monster)
        Rails.logger.info "Pokemon - #{monster[:name]} - was created"
      else
        mon.update(monster)
        Rails.logger.info "Pokemon - #{monster[:name]} - was updated"
      end
    end

    redirect_to pokemons_path()
  end

  def get_move_types
    (1..18).each do |num| 
      movetype = Poke::Dex.get_move_type(num)
      mt = MoveType.where(tid: movetype[:id])

      if mt.empty?
        m = MoveType.new(movetype)
        m.save
        Rails.logger.info "Move Type - #{movetype[:name]} - was created"
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pokemon
      @pokemon = Pokemon.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pokemon_params
      params.require(:pokemon).permit(:pid, :name, :weight, :height, :base_experience, :type, :sprite)
    end

    def format_pokemon_ids collection
      if collection.match(/,/) != nil
        collection.split(',')

      elsif collection.match(/\.\./) != nil
        collection = collection.split("..")
        start = collection[0]
        finish = collection[1]

        Range.new(start, finish)
        
      else 
        collection
      end
    end
end

app/helpers/pokemons_helper.rb
module PokemonsHelper
end

app/views/pokemons/_form.html.erb
<%= form_for(pokemon) do |f| %>
  <% if pokemon.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(pokemon.errors.count, "error") %> prohibited this pokemon from being saved:</h2>

      <ul>
      <% pokemon.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pokemons/collect.html.haml
= form_for :pokemon, url: {action: "update_create_pokemon"} do |f|
  %h2 collect

  %p= " For a single pokemon you can enter its name or pokemon id "

  %p= " This text box also excepts a comma separated list "

  %p= " Or you can do a range: 1..151 (recommended for starting out with) "
  
  = f.text_field :collection
  = f.submit

app/views/pokemons/edit.html.erb
<h1>Editing Pokemon</h1>

<%= render 'form', pokemon: @pokemon %>

<%= link_to 'Show', @pokemon %> |
<%= link_to 'Back', pokemons_path %>

app/views/pokemons/index.html.haml
.row
  = render partial: "layouts/pokemon_entry", locals: {pokemons: @pokemons, link: true}

app/views/pokemons/new.html.erb
<h1>New Pokemon</h1>

<%= render 'form', pokemon: @pokemon %>

<%= link_to 'Back', pokemons_path %>

app/views/pokemons/show.html.haml
.pokemon.show
  .pokemon-sprite
    = image_tag(@pokemon.sprite, :alt => "#{@pokemon.name} (#{@pokemon.pid})")
  .pokemon-name
    = @pokemon.name.capitalize
  .pokemon-types
    - mtone = MoveType.find_by_tid(@pokemon.typeone)
    .typeone= mtone.name.capitalize
    - if @pokemon.typetwo
      - mttwo = MoveType.find_by_tid(@pokemon.typetwo)
      .typetwo= mttwo.name.capitalize
  .pokemon-info
    .info.weight
      = "Weight: #{@pokemon.weight}"
    .info.height
      = "Height: #{@pokemon.height}"
    .info.base_exp
      = "Base Exp: #{@pokemon.base_experience}"


= link_to 'Edit', edit_pokemon_path(@pokemon)
|
= link_to 'Back', pokemons_path