config/routes.rb
Rails.application.routes.draw do
  
  resources :trainer_cards
  devise_for :trainers

  authenticated :trainer do
    root 'pokemons#index', as: :authenticated_root
  end

  unauthenticated :trainer do
    root "splash#index", as: :unauthenticated_root
  end
  

  resources :pokemons do
    collection do
      get 'collect'
      post 'update_create_pokemon'
    end
  end

  get 'trainer_card/for_trainer/:id' => 'trainer_cards#for_trainer', as: :trainers_card
end

app/views/layouts/_display_pokemon.html.haml
.pokemon.entry.col-sm-4{data: {id: pokemon.pid}}
    - if link 
        = link_to pokemon_path(pokemon.pid) do
            .sprite= image_tag(pokemon.sprite, :alt => "#{pokemon.name} (#{pokemon.pid})")
            .pokemon-name= pokemon.name.capitalize!
    - else 
        .sprite= image_tag(pokemon.sprite, :alt => "#{pokemon.name} (#{pokemon.pid})")
        .pokemon-name= pokemon.name.capitalize!

app/views/layouts/_nav_bar.html.haml
- if trainer_signed_in?
  .row
    .col-sm-12
      %nav.navbar.navbar-default
        .container
          %h1.pokemon.navbar-brand= "Pokémon"
          #navbarNav.collapse.navbar-collapse
            %ul.nav.navbar-nav
              %li.nav-item.nav-link= link_to "Pokémon", pokemons_path()
              %li.nav-item.nav-link= link_to "Collect", collect_pokemons_path()
              - if current_trainer.email != "profoak@gmail.com"
                %li.nav-item.nav-link= link_to "Trainer Card", trainers_card_path(current_trainer.id)
              %ul.nav.navbar-nav.trainer-nav.pull-right
                - if current_trainer
                  %li= link_to "Hello #{current_trainer.name}", edit_trainer_registration_path()
                  %li.divider= "|"
                  %li= link_to 'Sign out', destroy_trainer_session_path, method: :delete

app/views/layouts/_pokemon_entry.html.haml
- pokemons.each do |pokemon|
    = render partial: "layouts/display_pokemon", locals: {pokemon: pokemon, link: link}

app/views/layouts/application.html.haml
%html
%head
  %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
  %title Pokedex
  = csrf_meta_tags
  = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
  = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
%body
  = render partial: "layouts/nav_bar"

  .container
    - if notice
      %p.notice= notice
    - if alert
      %p.alert= alert

    = yield